### ISSUE TITLE
Sem retorno

### ISSUE THREAD

**Issue by felipecrf** [gamuzatech/gamuza_itaushopline-magento#10]
Olá! Não está tendo retorno do banco, tem que aprovar o boleto baixando a remessa direto no site do banco. Todas as formas de pagamento entram como "Cartão de Crédito" na página do cliente. Como resolveR?

**Comment by matneves** [comment]
Olá @felipecrf, é preciso informar a url de retorno nas configurações do módulo. Entretanto essa url não existe por padrão, deve ser desenvolvida. Como informa o readme do módulo:

> Capturando o Retorno
> 
> O endereço para Retorno do Tipo de Pagamento será composto da seguinte maneira:
> 
> HTTPS:// + URL de Retorno Cadastrada + URLRetorna do Pedido + parâmetros de retorno criptografados.
> 
> Exemplo:
> 
> URL de Retorno cadastrada no Módulo Itaú Shopline = http://www.minhaloja.com.br URL de retorno passada pelo lojista no pedido em questão = /final/retorno.php Dados de retorno criptografados=?DC=A345B456F456W456T56J3K678
> 
> Exemplo da chamada à URL final:
> 
> https://www.minhaloja.com.br/final/retorno.php?DC=A345B456F456W456T56J3K678
> 
> A página de retorno do pagamento deve receber os dados criptografados e chamar o método decripto, e, para acessar o conteúdo de cada campo é necessário usar os métodos que retornam seus conteúdos:
> 
> CodEmp - Código da Empresa ou Código do Site - Alfanumérico de 26 posições
> Pedido - Numero do Pedido - Numérico com 8 posições
> TipPag - Tipo de pagamento escolhido pelo comprador - Numérico com 2 posições: 01 para Pagamento à Vista (TEF ou CDC) 02 para Boleto 03 para Cartão Itaucard
