### ISSUE TITLE
Parâmetros do método decripto

### ISSUE THREAD

**Issue by matneves** [gamuzatech/gamuza_itaushopline-magento#11]
Estou desenvolvendo uma url de retorno e preciso saber quais os parâmetros o método decripto (`app/code/community/Gamuza/Itaushopline/Model/Itaucripto.php`) espera. Não consegui entender o quê colocar em $s e $s1 (string e string1), seria mais interessante criar variáveis com nomes mais sugestivos.

**Comment by eneiasramos** [comment]
Olá @matneves ! Tudo bem?

Use o método:

$dados = decripto ($dc, $chave);

Att,

**Comment by matneves** [comment]
Olá @eneiasramos,

Certo, estou utilizando desta forma, porém o "retorno" do método ficou em branco. Fui verificar e na linha 130 do Itaucripto.php o correto seria:

```
if($s2 != "")
```

e não:


```
if($s2 == "")
```

Inclusive estes outros, [1](https://github.com/gabrielrcouto/php-itaucripto/blob/master/Itaucripto.php) e [2](https://www.phpclasses.org/package/8449-PHP-Generate-a-key-to-make-payments-using-Itau-bank.html), exemplos da classe exibem a condição desta forma.

Após realizar esta alteração verifiquei que os caracteres de retorno eram extremamente aleatórios, até mesmo fora do que é possível exibir com o conjunto de fontes padrão do meu computador.

Exemplo utilizando o query_dc:
![captura de tela 2017-01-28 as 12 24 55](https://cloud.githubusercontent.com/assets/2514252/22397635/df45be18-e554-11e6-9f28-18e683e3f9e4.png)

O quê me levou a outro questionamento, qual dc deve ser utilizado o query ou submit? Como para mim nenhum dos dois estavam funcionando, criei um controller para funcionar como url de retorno, que iria salvar em log os acessos e os resultados, e cadastrei a url no admin, com https. Entretanto, o Itaú não acessou essa url em momento algum.

Você já passou por isso? Chegou a investigar esta classe e testar o seu funcionamento? Onde estou errando?

Abraços,
Mateus.
