### ISSUE TITLE
Botão de efetuar pagamento não imagem das configurações

### ISSUE THREAD

**Issue by fernandoperigolo** [gamuzatech/gamuza_itaushopline-magento#12]
O botão de efetuar pagamento está sendo montado como o código a seguir. Um simples botão submit sem estilo. A imagem do botão cadastrada no admin está sendo ignorada tanto no success quanto no minha conta e admin da loja.

```<input id="submit" name="" value="Enviar" type="submit" class=" submit">```

Também não achei um template para editar este botão, acredito que seja montado no código. Seria bom ter um template para a gente customizar a mensagem. Por exemplo, no checkout quero escrever um texto "Você será redirecionada para o site do Itau para imprimir o boleto", seria bem útil.

**Comment by FilipeSilvaCtba** [comment]
Olá @fernandoperigolo 

Você conseguiu resolver este estilo do botão?

Obrigado.

**Comment by eneiasramos** [comment]
Caros,

atualizei o módulo adicionando a classe e id shoplinebutton para posterior customização.

https://github.com/gamuzatech/gamuza_itaushopline-magento/commit/f91245e0430c90adc8bae134a6b577b7b51c6593

Att,
