### ISSUE TITLE
Ao comentar num pedido que está como Processando ele volta para o state cadastrado

### ISSUE THREAD

**Issue by fernandoperigolo** [gamuzatech/gamuza_itaushopline-magento#13]
Depois dos ajustes feitos em #8 , sempre que comento o pedido volta para o status que configurei no módulo.
Eu faturei um pedido, ele foi para processando. Inseri um comentário, ele voltou para Novo(que é o status que configurei).
Não pode ser assim. Acredito que o evento usado para colocar o state do pedido é muito genérico.

O que precisamos é, **no momento que o pedido é criado**, seja setado o state correspondente ao "Status dos Novos Pedidos" que eu configurei.

Eu sugiro que no campo Status dos Novos Pedidos tenha somente os status do state NEW e que, ao criar o pedido, seja setado o state NEW. Esta parte de setar o state ao criar o pedido que estava faltando aparentemente.

**Comment by eneiasramos** [comment]
@fernandoperigolo os ajustes foram revertidos. Por favor, atualize o seu módulo novamente.
