### ISSUE TITLE
Não foi possível gerar o código de transação para envio. Verifique as suas configurações.

### ISSUE THREAD

**Issue by brunohrp** [gamuzatech/gamuza_itaushopline-magento#15]
Em algumas compras aparece a mensagem: Não foi possível gerar o código de transação para envio. Verifique as suas configurações.

Aparece em apenas algumas transações a mensagem.

**Comment by eneiasramos** [comment]
Olá @brunohrp ! Tudo bem?

Segue: http://forum.gamuza.com.br/viewtopic.php?f=10&t=208&p=439#p439

Att,
