### ISSUE TITLE
Não foi possível gerar o código de transação para envio. Verifique as suas configurações.

### ISSUE THREAD

**Issue by brunohrp** [gamuzatech/gamuza_itaushopline-magento#16]
Você disse para verificar as configurações.

Mas como eu disse, todas as configurações estão corretas. Tanto que algumas compras funciona perfeitamente e em algumas compras não funciona.

**Comment by eneiasramos** [comment]
Tópico duplicado: http://forum.gamuza.com.br/viewtopic.php?f=10&t=208
