### ISSUE TITLE
Gerar o código de transação

### ISSUE THREAD

**Issue by renatoagomes** [gamuzatech/gamuza_itaushopline-magento#17]
Estou tentando utilizar esse módulo mas ainda nao consegui realizar um pedido com sucesso.

Estou travado na mensagem de erro: 

> Não foi possível gerar o código de transação para envio. Por favor, verifique as suas configurações.<br/>P183B175D211N8F238T108A155A166F237G54W165U217A1....

Lí o README.md, e parece que está faltando alguma informação na configuração. Mas não consigo identificar qual. 

Gostaria de saber se existe alguma maneira para identificar a partir da string gerada, ou qualquer orientação que possa ajudar a resolver o problema.

Estou logando todas as informações que sao passadas para o metodo geraDados do Itaucripto.php

```
	Mage::log('Debug order ItauSHOPLINE ********');
	Mage::log('$code   -->   ' . $code);
	Mage::log('$short_number   -->   ' . $short_number);
	Mage::log(str_replace ('.', "", number_format ($amount, 2, ', ', '.')) );
	Mage::log('$obs   -->   ' . $obs);
	Mage::log('$key   -->   ' . $key);
	Mage::log('$name   -->   ' . $name);
	Mage::log(strlen($tax_vat) == 14 ? '02' : '01' ); /* 01:CPF, 02:CNPJ */
	Mage::log('$tax_vat   -->   ' . $tax_vat);

	Mage::log('$street1   -->   ' . $street1);
	Mage::log('$street2   -->   ' . $street2);
	Mage::log('$postcode   -->   ' . $postcode);
	Mage::log('$city   -->   ' . $city);
	Mage::log('$region   -->   ' . $region);
	Mage::log('$bank_expiration   -->   ' . $bank_expiration);
	Mage::log('$return_url   -->   ' . $return_url);

	Mage::log('$obsadd1   -->   ' . $obsadd1);
	Mage::log('$obsadd2   -->   ' . $obsadd2);
	Mage::log('$obsadd3   -->   ' . $obsadd3);


    $submit_dc = Mage::getModel ('itaushopline/itaucripto')->geraDados(
    $code, $short_number, str_replace ('.', "", number_format ($amount, 2, ',', '.')), $obs, $key, $name, strlen($tax_vat) == 14 ? '02' : '01' /* 01:CPF, 02:CNPJ */, $tax_vat,
    $street1, $street2, $postcode, $city, $region, $bank_expiration, $return_url,
    $obsadd1, $obsadd2, $obsadd3
    );
```

A unica informação aparentemente nao está sendo passada é a $tax_vat. 

Se tiver qualquer orientação eu agradeço

**Comment by eneiasramos** [comment]
Olá @renatoagomes ! Tudo bem?

O campo taxvat é um campo necessário para o Shopline.

Você pode consultar os campos necessários para o correto funcionamento do módulo no link:

https://github.com/gamuzatech/gamuza_itaushopline-magento#perguntas-frequentes

Att,

**Comment by renatoagomes** [comment]
Valeu pela resposta rapida @eneiasramos 

Vou checar aqui.

**Comment by cfgalvani** [comment]
@renatoagomes Conseguiu resolver? Na minha loja mais antiga funciona certinho, mas na minha nova não está funcionando. Da o mesmo erro que falou acima. Uso o tema Porto com Onestepcheckout da Inovart..
