### ISSUE TITLE
Boleto com Registro

### ISSUE THREAD

**Issue by apzeiro** [gamuzatech/gamuza_itaushopline-magento#18]
Gostaria de saber se o módulo já atende à questão da necessidade dos boletos serem registrados?
Obrigado.

**Comment by eneiasramos** [comment]
Olá @apzeiro ! tudo bem?

Ainda não temos suporte a registro.

Att,

**Comment by apzeiro** [comment]
Alguma previsão?
Talvez ocorra ainda dentro do prazo limite estipulado?
Pergunto porque preciso adotar uma solução para alguns logistas e gostaria que fosse definitiva. Obrigado.
