### ISSUE TITLE
Botão para pagamento no Email

### ISSUE THREAD

**Issue by FilipeSilvaCtba** [gamuzatech/gamuza_itaushopline-magento#19]
Prezados,

Instalei o módulo e já esta funcionando normalmente. Fiz e paguei boleto de teste e já deu certo na conta de minha empresa.

O problema é que o botão para pagamento que é enviado para o email do cliente (email de confirmação de pedido) quando é clicado, retorna o seguinte erro no itaú:

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Loja não cadastrada no Itaú Shopline.(Erro 00)
--
SOS - Itaú Bankline
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Somente no botão do email dá este erro, no backend e ná pagina de sucesso do pedido ele redireciona para o itaú para pagamento sem problemas.

Ps: a loja está cadastrada com sucesso, e já passaram-se 48horas da homologação.

**Comment by FilipeSilvaCtba** [comment]
Update: Estava verificando no meu computador o email. Linux usando o Thunderbird. 

Neste software de email acontece o erro.

Fui ver em outro computador, o erro não ocorre acessando via webmail. E no windows, via windows live mail aparece um erro de javascript (imagem anexo).

Se clico sim para continuar executando scripts desta pagina, o botao funciona normalmente, caso contrario não.

Acredito que o thunderbird já está negando a execução deste script de forma automatica.
Em todo caso, fica ruim aparecer este erro para o cliente.

Alguma sugestão? [http://www.radiovenda.com.br/images/erro_javascript.png](url)

**Comment by eneiasramos** [comment]
Olá @FilipeSilvaCtba ! Tudo bem?

Qual a URL da sua loja?

Att,

**Comment by FilipeSilvaCtba** [comment]
@eneiasramos Olá, boa noite, tudo bem.

http://loja.silvalar.com.br

**Comment by eneiasramos** [comment]
Olá @FilipeSilvaCtba ! Tudo bem?

Fizemos um ajuste para o botão de pagamento funcionar com os clientes de e-mail Microsoft.

https://github.com/gamuzatech/gamuza_itaushopline-magento/commit/43283db709b2ef2613d6b0c80ebd6dd61afb9e3f

Att,
