### ISSUE TITLE
Erro 08 ao gerar boleto

### ISSUE THREAD

**Issue by MichelFrade** [gamuzatech/gamuza_itaushopline-magento#20]
Estou tendo problemas na hora de gerar o boleto, a página do itaú retorna o código de erro 08.

Existe algum arquivo de log para consuta? Se sim, aonde eu o encontro?

**Comment by eneiasramos** [comment]
Olá @MichelFrade ! Tudo bem?

Esse erro acontece quando algum campo não foi preenchido.

Por favor, consulte o nosso manual no link: https://github.com/gamuzatech/gamuza_itaushopline-magento#perguntas-frequentes e saiba como configurar corretamente o módulo do Itaú Shopline.

Att,
