### ISSUE TITLE
CEP Inválido

### ISSUE THREAD

**Issue by romereza** [gamuzatech/gamuza_itaushopline-magento#23]
Estou tendo um problema ao gerar os boletos.

Os pedidos são concluídos com sucesso, ao solicitar para  imprimir os boletos aparece uma mensagem CEP Inválido, o boleto é gerado mas não conseguimos pagar o mesmo não é registrado no itaushopline.

![image](https://user-images.githubusercontent.com/22554489/73361344-8e134d00-4283-11ea-8988-4e2e127370d1.png)

![image (1)](https://user-images.githubusercontent.com/22554489/73361360-94092e00-4283-11ea-977c-7a712e56e496.png)

![image (2)](https://user-images.githubusercontent.com/22554489/73361374-99667880-4283-11ea-991d-916d8dde9b75.png)

**Comment by eneiasramos** [comment]
@romereza você alterou a quantidade de linhas do endereço para 4?

**Comment by romereza** [comment]
> @romereza você alterou a quantidade de linhas do endereço para 4?

Olá @eneiasramos,

A configuração do endereço já estava para 4 linhas e estava funcionando normalmente.
Entrei em contato com o pessoal do ItauShoppline para debugar o erro e eles informaram que estava passando o CEP de forma errada, era para passar apenas números com 8 caracteres. Como no cadastro dos endereços para minha loja os CEPs são cadastrados com 9 dígitos pois possuem o hífen tive que fazer um ajuste no código e adicionar uma linha antes da chamada para gerar o boleto.

**.../Gamuza/Itaushopline/Model/Standard.php**

        $short_number = substr ($number, -8); /* Order number max. length for ItauShopLine */
        
        //Ln ADD
        $postcode = str_replace("-", "", $postcode);
        //Ln ADD

        $submit_dc = Mage::getModel ('itaushopline/itaucripto')->geraDados(
        $code, $short_number, str_replace ('.', "", number_format ($amount, 2, ',', '.')), $obs, $key, $name, strlen($tax_vat) == 14 ? '02' : '01' /* 01:CPF, 02:CNPJ */, $tax_vat,
        $street1, $street2, $postcode, $city, $region, $bank_expiration, $return_url,

**Comment by eneiasramos** [comment]
@romereza estranho porque validamos o CEP para enviar somente números para o Shopline:

[linha 114](
https://github.com/gamuzatech/gamuza_itaushopline-magento/blob/master/app/code/local/Gamuza/Itaushopline/Model/Standard.php#L114)

**Comment by romereza** [comment]
Estranho @eneiasramos tenho está mesma versão 0.0.2 instalada mas esta linha não está assim para mim.

Meu código tem apenas:
$postcode = $address->getPostcode ();

**Comment by eneiasramos** [comment]
Baixa a última versão em [ZIP](https://github.com/gamuzatech/gamuza_itaushopline-magento/archive/master.zip)

**Comment by romereza** [comment]
Vou fazer isso. Obrigado.

**Comment by eneiasramos** [comment]
@romereza disponha meu caro.
