### ISSUE TITLE
Pedido criado já entra como processing

### ISSUE THREAD

**Issue by fernandoperigolo** [gamuzatech/gamuza_itaushopline-magento#8]
Quando um pedido é criado e ainda está em aberto(boleto por exemplo) ele vai para o status que eu configurei no módulo.

Nesta situação, ao tentar inserir um comentário no pedido, só aparece opções de state processing e não do state do pedido.
Ao comentar, o pedido já vai para processing.
De alguma forma acredito que os pedidos estão sendo criados no state processing e não no state relacionado ao status que configurei no módulo.

**Comment by fernandoperigolo** [comment]
![screen shot 2017-01-12 at 16 28 28](https://cloud.githubusercontent.com/assets/5182178/21902747/411ba04e-d8e4-11e6-86b7-35df18479395.png)
Exemplo de um pedido que está como Aguardando Pagamento e ao tentar colocar um comentário não aparece esta opção de status. As opções de status que aparecem é do state processing.

Alguém me ajuda por favor?

**Comment by eneiasramos** [comment]
Olá @fernandoperigolo ! Tudo bem?

Adicionamos uma configuração no painel administrativo para estado de novos pedidos

Por favor, atualize o seu módulo.

Att,

**Comment by fernandoperigolo** [comment]
Oi, @eneiasramos . Fiz o teste e qualquer mudança que eu faço no pedido agora joga ele para este state que eu configurei.
A solução aplicada permite configurar status que não estão interligados aos states, isso causa danos inimagináveis do fluxo dos pedidos. Sugiro reverter totalmente esta mudança e garantir somente que o pedido vá para o state NEW ao criar o pedido.
Expliquei um pouco aqui #13
